### PR TITLE
add initWithCoder to allow initialization from nib

### PR DESCRIPTION
**Pull request by sdesimone**
The change is in BFNavigationController/BFNavigationController.m -- stylistic change in BFNavigationController/BFNavigationController.h, but that could be ignored.

Thanks.

### CODE REVIEW

**Comment by lucasderraugh** [comment]
What is the reasoning behind putting the navigationController property in the delegate protocol?

**Comment by sdesimone** [comment]
It seems to me that the majority of delegate methods use to specify the object that is sending the message as their first parameter. This is useful, e.g., when you share a single delegate across several delegating objects, so you can tell which is which. This is especially true with Apple classes. In any case, that was the "stylistic" change I was referring to, the other one is more substantial.

**Comment by lucasderraugh** [comment]
Right, but you would still have to setup the property on your own because there is no place that the navigationController will be automatically assigned for you. Also, I'm not trying to be annoying, but I'm curious how using initWithCoder would be beneficial if the frame is 0 and there is no controller. If there is a valid reason I'll gladly merge in the changes.

**Comment by sdesimone** [comment]
InitWithCoder is required if you ever use BFNavigationController in Interface Builder/Storyboard. About the delegate API, I am not sure I understand what you mean. Consider this scenario: you have a master controller (e.g., the app delegate) acting as the delegate for 2 different BFNavigationControllers. How would the master controller tell which BFNavigationController sent the delegate message? In any case, I think what is really useful is adding initWithCoder to support IB. The delegate API is really not that important and possibly it would not be a good idea to modify the delegate API due to backward compatibility considerations. Thanks.

**Comment by lucasderraugh** [comment]
But doesn't NSViewController already have a default implementation of NSCoding? Which I think also means you'd have to make a call to [super initWithCoder:]. I'm also not sure that I'd want to call the initWithFrame: with a zero frame, since I don't really want it to be a zero frame. I'll have to test this out.

I still can't see the delegate case though, because the property is on the BFNavigationController itself, so would you get it's own property to point to itself? How can the AppDelegate actually access this without the AppDelegate simply making a property of it's own to point to the BFNavigationController object?

**Comment by sdesimone** [comment]
About the first point, for some reason you need to define that method -- encoding/decoding also involves class-related information (class name, whatever), so the super implementation will not be enough. You can try it out in IB -- it will not work (I tried it out, then implemented initWithCoder. About the fact that [super initWithCoder] should be called, you are fully right here. Fully.

About the delegate issue, agreed that the class that creates the BFNavigationController objects shall keep a strong reference to them, at least to keep them alive. The delegate class can be a different one, e.g. a specialised class that is also instantiated by the same object that creates the controllers, and this one will receive the information about which controller fired the delegate method through the first argument. But even if we assume that creator object and delegate object are the same, you still need to know which controller has fired the delegate method -- if you have just one controller, no issue at all there. If you have more than one, well, the properties will not help you to tell which was the one.

**Comment by lucasderraugh** [comment]
Ok, If you want to add the change for the initWithCoder to call super I'll merge that (or I can add that in myself).

On the delegate thing, I just realized that this was in the protocol, not a property on the BFNavigationController itself, my bad. Last clarification though, if there is a single property for navigationController, then how would this in effect help with the multiple BFNavigationController case. Doesn't that mean that a delegate could only point to a single navigationController in this case. An explanation for that would be great, but if you could change up the initWithCoder: to call super, I'll take in the merge.

**Pull request closed without merging**
